spring:
  application:
    name: pricing-service
  datasource:
    url: jdbc:h2:mem:pricingdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    open-in-view: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always